### ISSUE TITLE
sfc problem

### ISSUE THREAD

**Issue by BlitheChen** [lrusso/Emulatrix#14]
@lrusso  :
I'm using emulatrix_ SuperNintendo.wasm But I need to add a parameter to solve some problems. Can you add this "block_invalid_vram_access" parameter to "settings_file" to modify snes9x2010. Just set the_ Add this parameter after file, as follows:

// All of these parameters you set work properly
.
.
.
settings_file += "video_message_pos_x = 0\n";
settings_file += "video_message_pos_y = 0\n";
settings_file += "menu_enable_widgets = false\n";

		
//But “block_invalid_vram_access” doesn't work，please implement this parameter setting
settings_file += "block_invalid_vram_access   = false\n";

**Comment by lrusso** [comment]
@BlitheChen This issue does not belong here. You must post the 'block_invalid_vram_access' issue here https://github.com/libretro/snes9x2010/issues.
