### ISSUE TITLE
kaiOS

### ISSUE THREAD

**Issue by david-p-s** [lrusso/Emulatrix#19]
Do you think it would be possible to port it to KaiOS in a simple way? 

https://en.wikipedia.org/wiki/KaiOS
https://www.martinkaptein.com/blog/porting-converting-web-apps-website-to-kai-os/

It would be a great app for the BananaPhone!

Some links...
https://sites.google.com/view/bananahackers/home
https://www.kaiostech.com/store/
https://github.com/strukturart/bHacker-store-client

**Comment by lrusso** [comment]
David,

Thank you for your post and suggestion. I'll consider it.

Best regards,
Leonardo
