### ISSUE TITLE
Include a JS GamePad library

### ISSUE THREAD

**Issue by DiGGeR2** [lrusso/Emulatrix#2]
Take a look here
[https://github.com/bwiklund/gamepad.js](https://github.com/bwiklund/gamepad.js)
it would be cool to have the gamepad working with emulatrix :)

**Comment by lrusso** [comment]
Thanks for the suggestion. I haven't be able to simulate keystrokes in the Emscripten environment that is been deployed in the LibRetro compilation, but I'll keep it in mind.

**Comment by monkeysuffrage** [comment]
Just chiming in, libretro has it's own gamepad support and I would be surprised if html5 gamepad api was nearly as good.
