### ISSUE TITLE
xbox controller and button mapping for sega genesis emu

### ISSUE THREAD

**Issue by drlight17** [lrusso/Emulatrix#21]
Hello! Very nice js emulator, but I have a trouble trying to map buttons to my xbox 360 wireless controller. I've added below strings to Emulatrix_SegaGenesis.htm:

// SETTING THE KEY FOR SAVE STATE
settings_file += "input_save_state = f5\n"; //keyboard saving
settings_file += "input_save_state_btn = 8\n"; //gamepad saving LS
				
// SETTING THE KEY FOR LOAD STATE
settings_file += "input_load_state = f9\n";
settings_file += "input_load_state_btn = 9\n"; //gamepad loading RS
No luck, noting happen when i fire this buttons. But if I add for example 4 instead of 8 and 5 instead of 9 then LB and RB works as expected. As I know button numbers are:

0 - A
1 - B
2 - X
3 - Y
4 - LB
5 - RB
6 - back
7 - start
8 - LS
9 - RS
Correct me if I'm wrong.
And also, setting
input_enable_hotkey_btn = any_button_number;
don't work ether for combination of buttons.
Please help me to figure out what am I doing wrong?

**Comment by lrusso** [comment]
Hello, the website receives the keystrokes (from any kind of device, not just a keyboard) and passes the keycode to the emulator for executing an action (moving, attacking, etc.). Emulatrix also works in high-end Android devices by providing a virtual joystick and buttons that sends fake keystrokes, so if some buttons are working with your controller, I'm guessing that you should check the xbox 360 controller mapping configuration.

If you browse to [https://keycode.info/](https://keycode.info/) and try to press any button, you should receive which key was pressed. That same key is the one that you should put in the Sega Genesis emulator. Also, below you will find the Retroarch documentation with all the reference to the key configuration.

```
Keyboard input. Will recognize letters ("a" to "z") and the following special keys (where "kp_" is for keypad keys):

left, right, up, down, enter, kp_enter, tab, insert, del, end, home,
rshift, shift, ctrl, alt, space, escape, add, subtract, kp_plus, kp_minus,
f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12,
num0, num1, num2, num3, num4, num5, num6, num7, num8, num9, pageup, pagedown,
keypad0, keypad1, keypad2, keypad3, keypad4, keypad5, keypad6, keypad7, keypad8, keypad9,
period, capslock, numlock, backspace, multiply, divide, print_screen, scroll_lock,
tilde, backquote, pause, quote, comma, minus, slash, semicolon, equals, leftbracket,
backslash, rightbracket, kp_period, kp_equals, rctrl, ralt
```

For last, the hotkey doesn't work properly in the Retroarch Emscripten porting.

Best regards,
Leonardo

**Comment by drlight17** [comment]
Thanks for the answer!

**Comment by drlight17** [comment]
Just to make a note. I found out gamepad button numbers using [this nice online tool](https://apps.nektro.net/gamepad/).
Now I did this and everything works amazing:
settings_file += "input_enable_hotkey = shift\n"; //for combination with shift key
settings_file += "input_enable_hotkey_btn = 8\n"; //for combination with gamepad back button
// SETTING THE KEY FOR SAVE STATE
settings_file += "input_save_state = f5\n"; //save with F5 key + hotkey above
settings_file += "input_save_state_btn = 10\n"; //save with gamepad LStick + hotkey_btn above
		
// SETTING THE KEY FOR LOAD STATE
settings_file += "input_load_state = f9\n"; //load with F9 key + hotkey above
settings_file += "input_load_state_btn = 11\n"; //load with gamepad RStick + hotkey_btn above
