### ISSUE TITLE
Problem with saving state.

### ISSUE THREAD

**Issue by ethanaobrien** [lrusso/Emulatrix#22]
I checked the console and found nothing. When I save the state for the first time when loading a game, it worked! I could load back up exactly where I was. But when I tried saving for the second time (Either after reloading and restoring state or saving for the 2nd time in 1 session) It always saves where you saved it the first time. I would assume this could be fixed by clearing cache but I have no idea how to do so. I am using the a snes game.

This project is the best emulator I've seen on the web! A little Advertising could make this insanely popular!

**Comment by lrusso** [comment]
Hello, thank you for your message and kind words. I just tried the SNES emulator in Chrome and Firefox, it takes some time to save and load states (only in SNES), but it worked the second save and load state that I did.

Best regards,
Leonardo

**Comment by ethanaobrien** [comment]
@lrusso The bug continues to happen no matter what I do. Would you like me to send a screen recording?

**Comment by lrusso** [comment]
https://user-images.githubusercontent.com/11498901/112565238-7e29c700-8dbb-11eb-936f-e945ec861b49.mp4
