### ISSUE TITLE
what would be the code to call the wasm file from an external server (url) 

### ISSUE THREAD

**Issue by leon-belmont** [lrusso/Emulatrix#24]
hola! gran proyecto!

Cuál sería el código para llamar al archivo wasm desde un servidor externo ( url )
algo como  http://url.com/Emulatrix_MAME32.wasm
Gracias de antemano!

Hi! great project!

What would be the code to call the wasm file from an external server (url)
something like http://url.com/Emulatrix_MAME32.wasm
Thanks in advance! sorry my bad english

**Comment by lrusso** [comment]
Not possible because of the CORS limitation.

Best regards,
Leonardo
