### ISSUE TITLE
in the future maybe add in the emulatrix

### ISSUE THREAD

**Issue by captaincomando** [lrusso/Emulatrix#28]
hi brother, I'm sharing, for maybe you add
my email: captaincomando@outlook.com.br
congratulations

Sega Master System & Game Gear

source code: https://github.com/gmarty/jsSMS
web test: https://gmarty.github.io/jsSMS/

Atari

source code: https://github.com/ppeccin/javatari.js
web test: https://javatari.org/

Playstation

source code: https://github.com/kootstra-rene/enge-js
web test: https://kootstra-rene.github.io/enge-js/

Playstation

source code: https://github.com/dkoluris/pseudo-js
web test: https://naden.co/pseudo/

Nintendo 64

source code: https://github.com/hulkholden/n64js
web test: https://hulkholden.github.io/n64js/

**Comment by lrusso** [comment]
Thanks for the message and suggestions.
