### ISSUE TITLE
How to open the game using the link on the site?

### ISSUE THREAD

**Issue by pavelbv2** [lrusso/Emulatrix#3]
Hello.
Sorry for my bad english!

Tell me, is it possible to somehow connect the ROM with the game through the link, and not upload from the computer?

**Comment by lrusso** [comment]
Yes, you can do a XMLHttpRequest like this one:

``
var oReq = new XMLHttpRequest();
oReq.open("GET", "/myromurl", true);
oReq.responseType = "arraybuffer";

oReq.onload = function (oEvent) {
  var arrayBuffer = oReq.response;
  if (arrayBuffer) {
    ROMDATA = new Uint8Array(arrayBuffer);
    // insert here the emulatrix loading script code
  }
};

oReq.send(null);
``

You can found out more about how to handle a request with binary data at:

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data
