### ISSUE TITLE
Autoload images/roms from url

### ISSUE THREAD

**Issue by Panther-42** [lrusso/Emulatrix#31]
How can i pass a rom file upon load from an url to autoload a file without the need for selecting?
It is possible?

**Comment by lrusso** [comment]
You can't. You must have an Emulatrix clone in your server and modify the Emulatrix source code in order to load ROM file from your server instead of selecting one from a local computer. More info at https://github.com/lrusso/Emulatrix/issues/3. Closed.

**Comment by Panther-42** [comment]
Then you can, after all....  if you modify the code.... thx by the way, i just saw that every other issues is about this; apologize about thea i opened an other one i just saw zero issues i was filtering badly... Seeing the issues about the same problem... have you ever considered that you implement that as an option? You might receive less messages like this... just saying, btw thx for the reply.
