### ISSUE TITLE
Could real time clock be added

### ISSUE THREAD

**Issue by CableTV1123** [lrusso/Emulatrix#34]
I was wonding if it is possible for a real time clock to be added because there are rom hacks that use it

just curious

**Comment by lrusso** [comment]
Not possible at the moment.

**Comment by ethanaobrien** [comment]
shouldnt this be marked as en enhancement instead of just being closed?

**Comment by lrusso** [comment]
I cannot do what is requested with JavaScript. Maybe that feature could be added by Libretro team.
