### ISSUE TITLE
DS Emulator

### ISSUE THREAD

**Issue by ZackandHack** [lrusso/Emulatrix#35]
Ok so basically I Love DS games and I was wonder if you could add emulator that can play DS games and while I understand it's laggy, I was wondering if its possible for the DS games to run more faster (I play on Chromebook) and an idea I had was to make it were you can make the frames go higher or lower as an option

**Comment by ZackandHack** [comment]
Also yes I am a new User

**Comment by lrusso** [comment]
Hello, not much to do for those laggy cases/devices, the same happened to me with an Android 5.0 tablet.

**Comment by ZackandHack** [comment]
Ok while I do understand that but could it be possible for you to add DS games?

**Comment by ethanaobrien** [comment]
shouldnt this be marked as an enhancement instead of just being closed since it is possible to implement a nintendo ds emulator?

**Comment by lrusso** [comment]
I am not a Emscripten developer. I used the ported projects from the Libretro team (when they worked) and I fix some minor JavaScript bugs.
