### ISSUE TITLE
Saving Issues

### ISSUE THREAD

**Issue by pavelbv2** [lrusso/Emulatrix#6]
Hello.
I discovered such a problem - If you load a game save and then make new saves, they will all be the same, the same as the one that was upload.

For example -
1 - I did save 1.state
2 - then I upload it
3 - play on and make new saves, 2.state 3.state 4.state and so on.
4 - I load 2.state or 3.state or 4.state
But all these saves will be in the same place where 1.save and not where I saved them.

It turns out that after loading the save, the new save does not work.

**Comment by lrusso** [comment]
Hello,

Thank you very much for your message and feedback. You can found this bug fixed in the latest version of Emulatrix.

Best regards and thanks again,
Leonardo
